// Function for Printing the Logo
void sigla()
{
	WINDOW *wnd;
	int nrows,ncols;
	wnd=initscr();
	start_color();
	/************************************************
	Intializing the Color pairs used in the Logo screen
	**************************************************/
	init_pair(1,COLOR_WHITE,COLOR_GREEN);
	init_pair(2,COLOR_WHITE,COLOR_BLUE);
	init_pair(3,COLOR_WHITE,COLOR_RED);
	init_pair(4,COLOR_WHITE,COLOR_YELLOW);
	init_pair(5,COLOR_BLACK,COLOR_YELLOW);
	cbreak();
	noecho();
	getmaxyx(wnd,nrows,ncols);
	clear();
	refresh();
	int rm=nrows/2;
	int cm=ncols/2;
	char d,*s;
	int i,j;
	attrset(COLOR_PAIR(1));
	/***************************************************
	ASCII Art print
	***************************************************/
	while(1)
	{
		i=12;
		s=" .----------------. " ;
		move(rm-i,cm-21);
		addstr(s);
			attrset(COLOR_PAIR(2));
			s=" .----------------. ";
			addstr(s);
		attrset(COLOR_PAIR(1));
		i--;
		s="| .--------------. |";
		move(rm-i,cm-21);
		addstr(s);
			attrset(COLOR_PAIR(2));
			s="| .--------------. |";
			addstr(s);
		attrset(COLOR_PAIR(1));
		i--;
		s="| |    _____     | |";
		move(rm-i,cm-21);
		addstr(s);
			attrset(COLOR_PAIR(2));
			s="| |     ____     | |";
			addstr(s);
		attrset(COLOR_PAIR(1));
		i--;
		s="| |   / ___ `.   | |";
		move(rm-i,cm-21);
		addstr(s);
			attrset(COLOR_PAIR(2));
			s="| |   .'    '.   | |";
			addstr(s);
		attrset(COLOR_PAIR(1));
		i--;
		s="| |  |_/___) |   | |";
		move(rm-i,cm-21);
		addstr(s);
			attrset(COLOR_PAIR(2));
			s="| |  |  .--.  |  | |";
			addstr(s);
		attrset(COLOR_PAIR(1));
		i--;
		s="| |   .'____.'   | |";
		move(rm-i,cm-21);
		addstr(s);
			attrset(COLOR_PAIR(2));
			s="| |  | |    | |  | |";
			addstr(s);	
		attrset(COLOR_PAIR(1));
		i--;
		s="| |  / /____     | |";
		move(rm-i,cm-21);
		addstr(s);
			attrset(COLOR_PAIR(2));
			s="| |  |  `--'  |  | |";
			addstr(s);
		attrset(COLOR_PAIR(1));
		i--;
		s="| |  |_______|   | |";
		move(rm-i,cm-21);
		addstr(s);
			attrset(COLOR_PAIR(2));
			s="| |   '.____.'   | |";
			addstr(s);
		attrset(COLOR_PAIR(1));
		i--;
		s="| |              | |";
		move(rm-i,cm-21);
		addstr(s);
			attrset(COLOR_PAIR(2));
			s="| |              | |";
			addstr(s);
		attrset(COLOR_PAIR(1));
		i--;
		s="| '--------------' |";
		move(rm-i,cm-21);
		addstr(s);
			attrset(COLOR_PAIR(2));
			s="| '--------------' |";
			addstr(s);
		attrset(COLOR_PAIR(1));
		i--;
		s=" '----------------' ";
		move(rm-i,cm-21);
		addstr(s);
			attrset(COLOR_PAIR(2));
			s=" '----------------' ";
			addstr(s);
		attrset(COLOR_PAIR(1));
		i--;
		attrset(COLOR_PAIR(3));
		s=" .----------------. " ;
		move(rm-i,cm-21);
		addstr(s);
			attrset(COLOR_PAIR(4));
			s=" .----------------. ";
			addstr(s);
		attrset(COLOR_PAIR(3));
		i--;
		s="| .--------------. |";
		move(rm-i,cm-21);
		addstr(s);
			attrset(COLOR_PAIR(4));
			s="| .--------------. |";
			addstr(s);
		attrset(COLOR_PAIR(3));
		i--;
		s="| |   _    _     | |";
		move(rm-i,cm-21);
		addstr(s);
			attrset(COLOR_PAIR(4));
			s="| |     ____     | |";
			addstr(s);
		attrset(COLOR_PAIR(3));
		i--;
		s="| |  | |  | |    | |";
		move(rm-i,cm-21);
		addstr(s);
			attrset(COLOR_PAIR(4));
			s="| |   .' __ '.   | |";
			addstr(s);
		attrset(COLOR_PAIR(3));
		i--;
		s="| |  | |__| |_   | |";
		move(rm-i,cm-21);
		addstr(s);
			attrset(COLOR_PAIR(4));
			s="| |   | (__) |   | |";
			addstr(s);
		attrset(COLOR_PAIR(3));
		i--;
		s="| |  |____   _|  | |";
		move(rm-i,cm-21);
		addstr(s);
			attrset(COLOR_PAIR(4));
			s="| |   .`____'.   | |";
			addstr(s);	
		attrset(COLOR_PAIR(3));
		i--;
		s="| |      _| |_   | |";
		move(rm-i,cm-21);
		addstr(s);
			attrset(COLOR_PAIR(4));
			s="| |  | (____) |  | |";
			addstr(s);
		attrset(COLOR_PAIR(3));
		i--;
		s="| |     |_____|  | |";
		move(rm-i,cm-21);
		addstr(s);
			attrset(COLOR_PAIR(4));
			s="| |  `.______.'  | |";
			addstr(s);
		attrset(COLOR_PAIR(3));
		i--;
		s="| |              | |";
		move(rm-i,cm-21);
		addstr(s);
			attrset(COLOR_PAIR(4));
			s="| |              | |";
			addstr(s);
		attrset(COLOR_PAIR(3));
		i--;
		s="| '--------------' |";
		move(rm-i,cm-21);
		addstr(s);
			attrset(COLOR_PAIR(4));
			s="| '--------------' |";
			addstr(s);
		attrset(COLOR_PAIR(3));
		i--;
		s=" '----------------' ";
		move(rm-i,cm-21);
		addstr(s);
			attrset(COLOR_PAIR(4));
			s=" '----------------' ";
			addstr(s);
		i--;
		move(nrows-2,ncols/2-15);
		attrset(COLOR_PAIR(0) | A_BLINK | A_DIM);
		s="(c) Razvan Buhaianu - 313CC  ";
		addstr(s);
		curs_set(0);
		refresh();
		//Using a 5 seconds delay
		usleep(5000000);
		break;
	}
}